#!/usr/bin/env python

import serial
import sys
import time
import os
import struct

device_="/dev/ttyACM0"

if __name__ == "__main__":

    if len(sys.argv) < 2:
        print "Usage lightbox <brightness>"
        sys.exit(1)
    if not os.path.exists(device_):
        print "Unable to find: %s" % device_
        sys.exit(1)
        
    val = int(sys.argv[1])&255;
    
    s = serial.Serial(device_, 9600, timeout=5000)
    id_ = s.read(4)
    if not id_ == "l!b2":
        print "no lightbox found on %s" % device_
        sys.exit(1)
        
    s.write(chr(val))
